from locust import HttpLocust, TaskSet

def home(l):
    l.client.get("/", verify=0, name="/")

def subs(l):
    l.client.get("/jobs/business-and-management-studies", verify=0, name="/jobs")
    l.client.get("/careers-advice/", verify=0, name="/careers")
    l.client.get("/categories/postdoc-jobs/", verify=0, name="categories")
    l.client.get("/phd", verify=0, name="/phd")

def bea(l):
    l.client.get("/job/BEA528/professor-in-defence-development-and-diplomacy/", verify=0, name="/BEA528")
    l.client.get("/job/BEC869/l-sl-in-law/", verify=0, name="/BEA869")
    l.client.get("/job/BEA812/professor-of-architecture/", verify=0, name="/BEA812")

def search(l):
    l.client.get("/search/?csrf=2ad3a107260e145e23766cf3c2a895ded4e6f38e&keywords=engineering&x=0&y=0", verify=0, name="/search")
    l.client.get("/search/?csrf=d0314809b8374305c1cad347789d4b1aa0d56256&category=0700&keywords=&category=0709&category=0701&jobtype=03&salary_from=35000&salary_to=80000&location=01&location=02&location=03&sector=222&sector=224&x=28&y=14", verify=0, name="/search")

def support(l):
    l.client.get("/css/base.css?1505129072", verify=1, name="/support")
    l.client.get("/css/home.css?1505129072", verify=1, name="/support")
    l.client.get("/css/jobs.css?1505129072", verify=1, name="/support")
    l.client.get("/css/site.css?1505129154", verify=1, name="/support")
    l.client.get("/fonts/fontawesome-webfont.eot?", verify=1, name="/support")
    l.client.get("/fonts/fontawesome-webfont.eot?v=4.3.0", verify=1, name="/support")
    l.client.get("/fonts/fontawesome-webfont.svg?v=4.3.0", verify=1, name="/support")
    l.client.get("/fonts/fontawesome-webfont.ttf?v=4.3.0", verify=1, name="/support")
    l.client.get("/fonts/fontawesome-webfont.woff2?v=4.3.0", verify=1, name="/support")
    l.client.get("/fonts/fontawesome-webfont.woff?v=4.3.0", verify=1, name="/support")
    l.client.get("/fonts/vjs.eot", verify=1, name="/support")
    l.client.get("/fonts/vjs.eot?", verify=1, name="/support")
    l.client.get("/fonts/vjs.svg", verify=1, name="/support")
    l.client.get("/fonts/vjs.ttf", verify=1, name="/support")
    l.client.get("/fonts/vjs.woff", verify=1, name="/support")
    l.client.get("/images/banners/125x60-button5-15051423683.png", verify=1, name="/support")
    l.client.get("/images/banners/china-final-new-14331471507-14464534440-14466540342-14700393695-15008893058.gif", verify=1, name="/support")
    l.client.get("/images/banners/COLLEGE-Featured-V1-14552847713-14653960667-15002788846.png", verify=1, name="/support")
    l.client.get("/images/banners/Featured-2017-Durham-University-15047811930.png", verify=1, name="/support")
    l.client.get("/images/banners/IRC_Featured-2017-15042724096.png", verify=1, name="/support")
    l.client.get("/images/banners/NCI-Featured2-15045205724.png", verify=1, name="/support")
    l.client.get("/images/banners/Ningbo-Featured-15041008533.png", verify=1, name="/support")
    l.client.get("/images/banners/RMIT_Premier_2017_-_LINKING-15046904721.png", verify=1, name="/support")
    l.client.get("/images/banners/spotlight_New-Featured-15009840755.png", verify=1, name="/support")
    l.client.get("/images/banners/Stirling-Featured-15046131184.png", verify=1, name="/support")
    l.client.get("/images/banners/Stirling-Spotlight-15046130336.png", verify=1, name="/support")
    l.client.get("/images/banners/WarwickSH_Featured-2017-15036491532.png", verify=1, name="/support")
    l.client.get("/images/banners/Warwick-Spotlight-Academic-Registrar-15036499170.png", verify=1, name="/support")
    l.client.get("/images/banners/WEG-Featured-Recruitment-Consultant-15042766546.png", verify=1, name="/support")
    l.client.get("/images/banners/WEG-Featured-Senior-Internal-Recruitment-Consultant-15047009092.png", verify=1, name="/support")
    l.client.get("/images/banners/WMG-SpotlightOpen_Day-15033157113.png", verify=1, name="/support")
    l.client.get("/images/china-pages/china-2.jpg", verify=1, name="/support")
    l.client.get("/images/china-pages/working-in-china", verify=1, name="/support")
    l.client.get("/images/china-pages/working-in-china/china-careers.gif", verify=1, name="/support")
    l.client.get("/images/china-pages/working-in-china/country-profile.jpg", verify=1, name="/support")
    l.client.get("/images/favicon.png", verify=1, name="/support")
    l.client.get("/images/global/action-bar_background.gif", verify=1, name="/support")
    l.client.get("/images/global/action-bar_background_tl.gif", verify=1, name="/support")
    l.client.get("/images/global/alt-boxed-bg.gif", verify=1, name="/support")
    l.client.get("/images/global/alt-boxed-bottom-bg.gif", verify=1, name="/support")
    l.client.get("/images/global/alt-boxed-heading-sprites.gif", verify=1, name="/support")
    l.client.get("/images/global/boxed-bg.gif", verify=1, name="/support")
    l.client.get("/images/global/boxed-bottom-bg.gif", verify=1, name="/support")
    l.client.get("/images/global/boxed-heading-sprites.gif", verify=1, name="/support")
    l.client.get("/images/global/boxed-top-bg.gif", verify=1, name="/support")
    l.client.get("/images/global/briefcase.png", verify=1, name="/support")
    l.client.get("/images/global/buttons/featured-employers.png", verify=1, name="/support")
    l.client.get("/images/global/buttons/find-jobs.gif", verify=1, name="/support")
    l.client.get("/images/global/buttons/view-all-jobs.gif", verify=1, name="/support")
    l.client.get("/images/global/favorite.png", verify=1, name="/support")
    l.client.get("/images/global/forms/bevelled-input_bg.gif", verify=1, name="/support")
    l.client.get("/images/global/gradiant-white-box/box-bottom-left.gif", verify=1, name="/support")
    l.client.get("/images/global/gradiant-white-box/box-bottom-right.gif", verify=1, name="/support")
    l.client.get("/images/global/gradiant-white-box/box-top-left.gif", verify=1, name="/support")
    l.client.get("/images/global/gradiant-white-box/box-top-right.gif", verify=1, name="/support")
    l.client.get("/images/global/gradiant-white-box/left.gif", verify=1, name="/support")
    l.client.get("/images/global/gradiant-white-box/right.gif", verify=1, name="/support")
    l.client.get("/images/global/great-jobs-bright-people.gif", verify=1, name="/support")
    l.client.get("/images/global/header/background.gif", verify=1, name="/support")
    l.client.get("/images/global/header/navigation_tab_left.gif", verify=1, name="/support")
    l.client.get("/images/global/header/navigation_tab_right.gif", verify=1, name="/support")
    l.client.get("/images/global/header/recruiters_tab_left.gif", verify=1, name="/support")
    l.client.get("/images/global/header/recruiters_tab_right.gif", verify=1, name="/support")
    l.client.get("/images/global/icons/back-to-top.gif", verify=1, name="/support")
    l.client.get("/images/global/icons/enlarge_icon.gif", verify=1, name="/support")
    l.client.get("/images/global/icons/jobseeker/20x20_doc.png", verify=1, name="/support")
    l.client.get("/images/global/icons/jobseeker/20x20_email.png", verify=1, name="/support")
    l.client.get("/images/global/icons/jobseeker/20x20_mobile.png", verify=1, name="/support")
    l.client.get("/images/global/icons/jobseeker/20x20_person.png", verify=1, name="/support")
    l.client.get("/images/global/icons/jobseeker/20x20_rss.png", verify=1, name="/support")
    l.client.get("/images/global/icons/print.gif", verify=1, name="/support")
    l.client.get("/images/global/icons/sets/famfamfam/page_white_acrobat.png", verify=1, name="/support")
    l.client.get("/images/global/icons/tick.gif", verify=1, name="/support")
    l.client.get("/images/global/jobs_ac_uk-logo.gif", verify=1, name="/support")
    l.client.get("/images/global/jobs_ac_uk-logo-grey.gif", verify=1, name="/support")
    l.client.get("/images/global/light-shade-box/bottom-left.gif", verify=1, name="/support")
    l.client.get("/images/global/light-shade-box/bottom-right.gif", verify=1, name="/support")
    l.client.get("/images/global/light-shade-box/top-left.gif", verify=1, name="/support")
    l.client.get("/images/global/light-shade-box/top-right.gif", verify=1, name="/support")
    l.client.get("/images/global/light-shade-box/top-right-with-line.gif", verify=1, name="/support")
    l.client.get("/images/global/navigation/sub-menu/arrows-blue.png", verify=1, name="/support")
    l.client.get("/images/global/navigation/sub-menu/nav-bg-grey.gif", verify=1, name="/support")
    l.client.get("/images/global/navigation/sub-menu/tab-left-blue.gif", verify=1, name="/support")
    l.client.get("/images/global/navigation/sub-menu/tab-left-blue-white.gif", verify=1, name="/support")
    l.client.get("/images/global/purple-shade-box/bottom-left.gif", verify=1, name="/support")
    l.client.get("/images/global/purple-shade-box/bottom-right.gif", verify=1, name="/support")
    l.client.get("/images/global/purple-shade-box/top-left-with-line.gif", verify=1, name="/support")
    l.client.get("/images/global/purple-shade-box/top-right-with-line.gif", verify=1, name="/support")
    l.client.get("/images/global/sharing/clouds-icon-small.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/facebook.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/facebook-sm.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/gplus-sm.png", verify=1, name="/support")
    l.client.get("/images/global/sharing_icons.gif", verify=1, name="/support")
    l.client.get("/images/global/sharing/linkedin.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/linkedin-sm.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/mail-icon-small.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/people-icon-small.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/twitter.png", verify=1, name="/support")
    l.client.get("/images/global/sharing/twitter-sm.png", verify=1, name="/support")
    l.client.get("/images/global/sign-up-now.gif", verify=1, name="/support")
    l.client.get("/images/global/single-box/blue-bg.gif", verify=1, name="/support")
    l.client.get("/images/global/tab-active.gif", verify=1, name="/support")
    l.client.get("/images/global/tab.gif", verify=1, name="/support")
    l.client.get("/images/jobs/mobile-app-bg.png", verify=1, name="/support")
    l.client.get("/images/recruiters/home/slider/pagination.png", verify=1, name="/support")
    l.client.get("/images/recruiters/tick.png", verify=1, name="/support")
    l.client.get("/images/resources/blog.png", verify=1, name="/support")
    l.client.get("/images/resources/ebooks.png", verify=1, name="/support")
    l.client.get("/images/resources/videos.png", verify=1, name="/support")
    l.client.get("/images/resources/vlogs.png", verify=1, name="/support")
    l.client.get("/images/sectors/business-jobs.jpg", verify=1, name="/support")
    l.client.get("/js/bundle.min.js?1505129162", verify=1, name="/support")
    l.client.get("/js/site.js?1505129155", verify=1, name="/support")
    l.client.get("/js/vendor.js?1505129158", verify=1, name="/support")
    l.client.get("/robots.txt", verify=1, name="/support")

class UserBehavior(TaskSet):
    tasks = {home:10, subs:5, bea:6, search:7, support:2}

class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait=8000
    max_wait=12000
